"""empty message

Revision ID: 1c339476f2f5
Revises: 4b4ae287fc8c
Create Date: 2014-05-02 15:57:38.551862

"""

# revision identifiers, used by Alembic.
revision = '1c339476f2f5'
down_revision = '4b4ae287fc8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['mobile'], [u'person.mobile'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'person', 'isAdmin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'person', sa.Column('isAdmin', sa.BOOLEAN(), nullable=True))
    op.drop_table('admins')
    ### end Alembic commands ###
