"""empty message

Revision ID: 22f624717826
Revises: None
Create Date: 2015-03-20 21:07:45.175250

"""

# revision identifiers, used by Alembic.
revision = '22f624717826'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('shortname', sa.String(length=10), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lane')
    )
    op.create_table('twilio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_sid', sa.String(length=200), nullable=True),
    sa.Column('auth_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betting_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.Column('horse', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse'], [u'horse.id'], ),
    sa.ForeignKeyConstraint(['person'], [u'person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['mobile'], [u'person.mobile'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('bet_history')
    op.drop_table('betting_status')
    op.drop_table('twilio_config')
    op.drop_table('horse')
    op.drop_table('person')
    ### end Alembic commands ###
