"""empty message

Revision ID: 34683a53959
Revises: 22f624717826
Create Date: 2015-04-25 15:28:03.556706

"""

# revision identifiers, used by Alembic.
revision = '34683a53959'
down_revision = '22f624717826'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
