"""empty message

Revision ID: 4236d76a35f5
Revises: 9f97b2ab2c0
Create Date: 2014-04-29 18:35:17.795421

"""

# revision identifiers, used by Alembic.
revision = '4236d76a35f5'
down_revision = '9f97b2ab2c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betting_status')
    ### end Alembic commands ###
