"""empty message

Revision ID: 4b4ae287fc8c
Revises: 4236d76a35f5
Create Date: 2014-04-29 21:23:02.971373

"""

# revision identifiers, used by Alembic.
revision = '4b4ae287fc8c'
down_revision = '4236d76a35f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twilio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_sid', sa.String(length=200), nullable=True),
    sa.Column('auth_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twilio_config')
    ### end Alembic commands ###
