"""empty message

Revision ID: 9f97b2ab2c0
Revises: 39e762193f3c
Create Date: 2014-04-27 19:59:10.341387

"""

# revision identifiers, used by Alembic.
revision = '9f97b2ab2c0'
down_revision = '39e762193f3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
